### ISSUE TITLE
[BUG] GraphDB backend errors out in certain conditions when request is sent from API

### ISSUE THREAD

**Issue by surchs** [neurobagel/api#139]
In 3396234 I have changed the graph backend from Stardog to GraphDB. This works well. However certain queries that previously passed now fail when sent from the API. 

Here are queries we have observed to:

- fail
  - age_min=5, age_max=10
  - age_min=10, age_max=11

- not fail
  - empty (full) query
  - age_min=20, age_max=24

when sent from the API. 
Other things we have observed:

- queries that fail when sent from the API succeed from either the graphDB workbench web UI or when sent direct via curl to the SPARQL endpoint. However they take unacceptably long to complete e.g. > 10 seconds. 
- By comparison, queries that complete when sent from the API also succeed when sent via curl or web UI, but only take less than 1 second to complete.

The specific error messages we observe on the

API:
```
httpx.ReadTimeout: timed out
```

GRAPH
```
[INFO ] 2023-08-08 16:21:24,647 [repositories/openneuro | c.o.g.s.h.GraphDBQueryResultHandler] POST query -783668637
[ERROR] 2023-08-08 16:21:38,990 [repositories/openneuro | c.o.g.s.TupleQueryResultView] Serialization error
org.eclipse.rdf4j.query.TupleQueryResultHandlerException: com.fasterxml.jackson.core.JsonGenerationException: Current context not Array but Object
	at org.eclipse.rdf4j.query.resultio.sparqljson.AbstractSPARQLJSONWriter.endQueryResult(AbstractSPARQLJSONWriter.java:205)
	at org.eclipse.rdf4j.query.resultio.sparqljson.SPARQLResultsJSONWriter.endQueryResult(SPARQLResultsJSONWriter.java:27)
	at com.ontotext.graphdb.sesame.CatchHandler.processWithBuffer(CatchHandler.java:150)
	at com.ontotext.graphdb.sesame.TupleQueryResultView.renderInternal(TupleQueryResultView.java:90)
	at org.eclipse.rdf4j.http.server.repository.QueryResultView.render(QueryResultView.java:66)
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1406)
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1150)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:555)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at com.ontotext.forest.security.AdminDelegatingFilterProxy.doFilter(AdminDelegatingFilterProxy.java:82)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at com.ontotext.forest.clusterproxy.ClusterFilterBean.doFilter(ClusterFilterBean.java:73)
	at com.ontotext.forest.clusterproxy.ClusterLoadBalancerFilter.doFilterInternal(ClusterLoadBalancerFilter.java:25)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at com.ontotext.forest.core.request.RequestFilter.doFilterInternal(RequestFilter.java:47)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at com.github.ziplet.filter.compression.CompressingFilter.doFilter(CompressingFilter.java:263)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.fasterxml.jackson.core.JsonGenerationException: Current context not Array but Object
	at com.fasterxml.jackson.core.JsonGenerator._reportError(JsonGenerator.java:2849)
	at com.fasterxml.jackson.core.json.WriterBasedJsonGenerator.writeEndArray(WriterBasedJsonGenerator.java:298)
	at org.eclipse.rdf4j.query.resultio.sparqljson.AbstractSPARQLJSONWriter.endQueryResult(AbstractSPARQLJSONWriter.java:200)
	... 52 common frames omitted
```

**Comment by surchs** [comment]
@alyssadai please add any discoveries or notes I missed

**Comment by surchs** [comment]
> @surchs And does the failure consistently produce the same error message?

yes it did. We have since figured out that the error is happening because the API times out after waiting for a response for 5 seconds - and then the graph apparently has an error because of that.

**Comment by surchs** [comment]
I'm closing this issue because we now know that it is linked to the API timing out for queries that take too long - and this then causes the observed (and cryptic) error message from graphDB.
